### ISSUE TITLE
Implement binary hash code

### ISSUE THREAD

**Issue by deepiksdev** [deepiksdev/torch#11]
See https://github.com/szagoruyko/loadcaffe

**Comment by Lolitawxc** [comment]
@deepiksdev  Is that a problem ?
License

The data used to train this model comes from the ImageNet project, which distributes its database to researchers who agree to a following term of access: "Researcher shall use the Database only for non-commercial research and educational purposes." Accordingly, this model is distributed under a non-commercial license.

from loadcaffe->binary hash code  https://gist.github.com/kevinlin311tw/266d4150a1db5810398e

**Comment by deepiksdev** [comment]
@Lolitawxc 

>  Is that a problem ?
License

Yes, that is a problem. I am now going to close this issue.
